server:
  port: 8080

logging:
  level:
    com.hectormaturano.technicaltest: info

spring:
  datasource:
    url: jdbc:h2:mem:techical-test
    username: technicalT
    password: technic@lT
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration,classpath:/db/testdata
    username: technicalT
    password: technic@lT